DROP DATABASE IF EXISTS HOME_TASK;
CREATE DATABASE HOME_TASK;
USE HOME_TASK;

CREATE TABLE CUSTOMER (
	ID 			INT				AUTO_INCREMENT,
    NAME 		VARCHAR(60)		NOT NULL,
    ADDRESS  	VARCHAR(180)	NOT NULL,
    DISCOUNT 	DOUBLE			NOT NULL,
    CONSTRAINT CUSTOMER$PK_ID PRIMARY KEY(ID)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE STORE (
	ID 			INT				AUTO_INCREMENT,
    NAME 	 	VARCHAR(60)		NOT NULL,
    ADDRESS  	VARCHAR(180)	NOT NULL,
    COMMISSION 	DOUBLE			NOT NULL,
    CONSTRAINT STORE$PK_ID PRIMARY KEY(ID)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE BOOK (
	ID 			INT				AUTO_INCREMENT,
    NAME 		VARCHAR(60)		NOT NULL,
    COST 		DOUBLE			NOT NULL,
    STORE_HOUSE VARCHAR(180)	NOT NULL,
    COUNT		INT				NOT NULL,
    CONSTRAINT BOOK$PK_ID PRIMARY KEY(ID)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE ORDERS (
	ID 			INT		AUTO_INCREMENT,
    ORDER_DATE	DATE	NOT NULL,
    CUSTOMER_ID	INT		NOT NULL,
    BOOK_ID		INT		NOT NULL,
    STORE_ID	INT		NOT NULL,
	COUNT		INT		NOT NULL,
    PRICE	 	DOUBLE	NOT NULL,
    CONSTRAINT ORDERS$PK_ID PRIMARY KEY(ID),
    CONSTRAINT ORDERS$FK_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID)
    REFERENCES CUSTOMER(ID) ON DELETE CASCADE,
    CONSTRAINT ORDERS$FK_STORE_ID FOREIGN KEY(STORE_ID)
    REFERENCES STORE(ID) ON DELETE CASCADE,
    CONSTRAINT ORDERS$FK_BOOK_ID FOREIGN KEY(BOOK_ID)
    REFERENCES BOOK(ID) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

INSERT INTO CUSTOMER(NAME, ADDRESS, DISCOUNT)
VALUES	('CUSTOMER_NAME1', 'CUSTOMER_ADDRESS1', 12.1),
		('CUSTOMER_NAME2', 'CUSTOMER_ADDRESS2', 12.2),
		('CUSTOMER_NAME3', 'CUSTOMER_ADDRESS3', 12.3),
		('CUSTOMER_NAME4', 'CUSTOMER_ADDRESS4', 12.4);
        
INSERT INTO STORE(NAME, ADDRESS, COMMISSION)
VALUES	('STORE_NAME1', 'STORE_ADDRESS1', 4.1),
		('STORE_NAME1', 'STORE_ADDRESS1', 4.2),
		('STORE_NAME1', 'STORE_ADDRESS1', 4.3),
		('STORE_NAME1', 'STORE_ADDRESS1', 4.4);
        
INSERT INTO BOOK(NAME, STORE_HOUSE, COST, COUNT)
VALUES	('STORE_NAME1', 'STORE_ADDRESS1', 67.1, 9),
		('STORE_NAME1', 'STORE_ADDRESS1', 67.2, 8),
		('STORE_NAME1', 'STORE_ADDRESS1', 67.3, 7),
		('STORE_NAME1', 'STORE_ADDRESS1', 67.4, 6);
        
INSERT INTO ORDERS(ORDER_DATE, COUNT, PRICE, CUSTOMER_ID, BOOK_ID, STORE_ID)
VALUES	(NOW(), 1, 678, 1, 1, 3),
		(NOW(), 2, 438, 4, 2, 2),
		(NOW(), 5, 612, 3, 3, 1),
		(NOW(), 3, 876, 2, 4, 4),
		(NOW(), 1, 118, 4, 1, 3),
		(NOW(), 2, 678, 3, 2, 2),
		(NOW(), 1, 448, 2, 3, 1);
        
DROP USER IF EXISTS 'HOME_TASK_USER'@'localhost';
CREATE USER 'HOME_TASK_USER'@'localhost' IDENTIFIED BY 'HOME_TASK_PASS';
GRANT ALL PRIVILEGES ON HOME_TASK.* TO 'HOME_TASK_USER'@'localhost';
